Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-07, with the labels that each got.

#173 refactor: Button component
  packages/react-styled-ui/src/Button/index.js
  packages/react-styled-ui/src/Button/styles.js
  packages/styled-ui-docs/pages/button.mdx
  packages/styled-ui-docs/pages/buttonbase.mdx
  packages/styled-ui-docs/pages/buttongroup.mdx
Labels: 👷 refactor (improvement)

#175 refactor: Radio component
  packages/react-styled-ui/src/Radio/index.js
  packages/react-styled-ui/src/Radio/styles.js
  packages/styled-ui-docs/pages/radio.mdx
  packages/styled-ui-docs/pages/radiogroup.mdx
Labels: 👷 refactor (improvement)

#174 refactor: Checkbox component
  packages/react-styled-ui/src/Checkbox/index.js
  packages/react-styled-ui/src/Checkbox/styles.js
  packages/styled-ui-docs/pages/checkbox.mdx
  packages/styled-ui-docs/pages/checkboxgroup.mdx
Labels: 👷 refactor (improvement)

#171 Feat/badge component next
  packages/react-styled-ui/src/Badge/index.js
  packages/react-styled-ui/src/Badge/styles.js
  packages/styled-ui-docs/pages/badge.mdx
Labels: 🔎 review required, 🚀 feature (enhancement), 🛑 breaking change

#181 chore: update checkbox icon after HIE reviewed
  packages/react-styled-ui/src/Checkbox/index.js
  packages/react-styled-ui/src/theme/icons.js
Labels: 🔎 review required

#179 Feature/menu component
  packages/react-styled-ui/src/Divider/index.js
  packages/react-styled-ui/src/Menu/Menu.js
  packages/react-styled-ui/src/Menu/MenuDivider.js
  packages/react-styled-ui/src/Menu/MenuGroup.js
  packages/react-styled-ui/src/Menu/MenuItem.js
  packages/react-styled-ui/src/Menu/MenuList.js
  packages/react-styled-ui/src/Menu/index.js
  packages/react-styled-ui/src/Menu/styles.js
  packages/react-styled-ui/src/MenuButton/index.js
  packages/react-styled-ui/src/MenuButton/styles.js
  packages/react-styled-ui/src/index.js
  packages/react-styled-ui/src/theme/icons.js
  packages/react-styled-ui/src/utils/usePrevious.js
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/menu.mdx
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/pages/tooltip.mdx
Labels: 🔎 review required, 🚀 feature (enhancement)

#186 docs: fix import typo
  packages/styled-ui-docs/pages/menu.mdx
Labels: 🐞 bug

#185 fix: ensure a minimum width for the close button in a flexbox layout
  packages/react-styled-ui/src/Alert/styles.js
  packages/react-styled-ui/src/AlertToast/styles.js
  packages/react-styled-ui/src/Drawer/styles.js
  packages/react-styled-ui/src/Modal/styles.js
  packages/react-styled-ui/src/Popover/styles.js
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/Tag/styles.js
  packages/react-styled-ui/src/Toast/styles.js
Labels: 🐞 bug

#188 fix: site layout style
  packages/styled-ui-docs/components/Header.jsx
  packages/styled-ui-docs/components/SideNav.jsx
  packages/styled-ui-docs/pages/_app.js
Labels: 🔎 review required, 🚀 feature (enhancement)

#176 Feature/light theme development
  .gitignore
  packages/react-styled-ui/src/Input/styles.js
Labels: 🔎 review required

#189 fix: multiple selected
  packages/styled-ui-docs/components/SideNav.jsx
Labels: 🐞 bug, 🔎 review required

#190 Add Light theme for Button
  packages/react-styled-ui/src/Button/styles.js
Labels: 🔎 review required

#194 feat: add light theme for Radio Component
  packages/react-styled-ui/src/Radio/styles.js
Labels: 🔎 review required

#195 fix(MDXComponents): change mdx and codeBlock styles
  packages/styled-ui-docs/components/Code.jsx
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/MDXComponents.jsx
  packages/styled-ui-docs/prism-themes/styled-ui.js
Labels: 🔎 review required, 🚀 feature (enhancement)

#196 docs: change theme pages style
  packages/styled-ui-docs/pages/borders.mdx
  packages/styled-ui-docs/pages/breakpoints.mdx
  packages/styled-ui-docs/pages/positions.mdx
  packages/styled-ui-docs/pages/shadows.mdx
  packages/styled-ui-docs/pages/sizes.mdx
  packages/styled-ui-docs/pages/spacing.mdx
  packages/styled-ui-docs/pages/typography.mdx
Labels: 🔎 review required, 🚀 feature (enhancement)

#193 breaking: deprecate AlertToast and add new props to Toast
  packages/react-styled-ui/src/Toast/index.js
  packages/react-styled-ui/src/Toast/styles.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/alerttoast.mdx
  packages/styled-ui-docs/pages/toast.mdx
  packages/styled-ui-docs/pages/usetoast.mdx
Labels: 👷 refactor (improvement), 🛑 breaking change

#201 docs: change wording
  packages/styled-ui-docs/pages/alert.mdx
  packages/styled-ui-docs/pages/button.mdx
  packages/styled-ui-docs/pages/checkbox.mdx
  packages/styled-ui-docs/pages/getting-started.mdx
  packages/styled-ui-docs/pages/link.mdx
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/pages/radio.mdx
  packages/styled-ui-docs/pages/spinner.mdx
  packages/styled-ui-docs/pages/tooltip.mdx
Labels: 📝 documentation, 🔎 review required
