Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-08, with the labels that each got.

#206 docs: updated the theme wordings and color "black:emphasis" value changed
  packages/react-styled-ui/src/Alert/styles.js
  packages/react-styled-ui/src/AlertToast/styles.js
  packages/react-styled-ui/src/Button/styles.js
  packages/react-styled-ui/src/Checkbox/styles.js
  packages/react-styled-ui/src/Drawer/styles.js
  packages/react-styled-ui/src/Modal/styles.js
  packages/react-styled-ui/src/Popover/styles.js
  packages/react-styled-ui/src/Tabs/styles.js
  packages/react-styled-ui/src/Toast/styles.js
  packages/styled-ui-docs/components/Header.jsx
  packages/styled-ui-docs/components/MDXComponents.jsx
  packages/styled-ui-docs/pages/borders.mdx
  packages/styled-ui-docs/pages/breakpoints.mdx
  packages/styled-ui-docs/pages/button.mdx
  packages/styled-ui-docs/pages/buttongroup.mdx
  packages/styled-ui-docs/pages/colors.mdx
  packages/styled-ui-docs/pages/positions.mdx
  packages/styled-ui-docs/pages/shadows.mdx
  packages/styled-ui-docs/pages/sizes.mdx
  packages/styled-ui-docs/pages/spacing.mdx
  packages/styled-ui-docs/pages/toast.mdx
  packages/styled-ui-docs/pages/typography.mdx
  packages/styled-ui-theme/src/base.js
Labels: 🔎 review required, 🚀 feature (enhancement)

#207 chore: adjust the width for icon button
  packages/styled-ui-docs/pages/buttongroup.mdx
Labels: 🐞 bug, 📝 documentation

#208 fix: change Icon component property
  packages/react-styled-ui/src/Accordion/index.js
  packages/react-styled-ui/src/Alert/index.js
  packages/react-styled-ui/src/AlertToast/index.js
  packages/react-styled-ui/src/Checkbox/index.js
  packages/react-styled-ui/src/Drawer/DrawerContent.js
  packages/react-styled-ui/src/Icon/index.js
  packages/react-styled-ui/src/MenuButton/index.js
  packages/react-styled-ui/src/Modal/ModalContent.js
  packages/react-styled-ui/src/SearchInput/index.js
  packages/react-styled-ui/src/Select/index.js
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/Toast/index.js
  packages/styled-ui-docs/pages/controlbox.mdx
  packages/styled-ui-docs/pages/icon.mdx
Labels: 👷 refactor (improvement), 🔎 review required

#205 feat: consistent background color style for form control components
  packages/react-styled-ui/src/Input/styles.js
  packages/react-styled-ui/src/Select/styles.js
  packages/react-styled-ui/src/Textarea/styles.js
Labels: 👷 refactor (improvement)

#202 feat: Basic pagination component
  packages/react-styled-ui/src/Pagination/index.js
  packages/react-styled-ui/src/index.js
  packages/react-styled-ui/src/usePagination/index.js
  packages/react-styled-ui/src/utils/useControlled.js
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/pagination.mdx
Labels: 🚀 feature (enhancement)

#203 feat: add support to TMIcon #146
  packages/react-styled-ui/src/Accordion/index.js
  packages/react-styled-ui/src/Alert/index.js
  packages/react-styled-ui/src/AlertToast/index.js
  packages/react-styled-ui/src/Checkbox/index.js
  packages/react-styled-ui/src/Drawer/DrawerContent.js
  packages/react-styled-ui/src/Icon/index.js
  packages/react-styled-ui/src/Icon/tmIconMap.js
  packages/react-styled-ui/src/Icon/tmIconSvgMap.js
  packages/react-styled-ui/src/MenuButton/index.js
  packages/react-styled-ui/src/Modal/ModalContent.js
  packages/react-styled-ui/src/SVGIcon/index.js
  packages/react-styled-ui/src/SearchInput/index.js
  packages/react-styled-ui/src/Select/index.js
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/Toast/index.js
  packages/react-styled-ui/src/theme/icons.js
  packages/react-styled-ui/src/theme/index.js
  packages/styled-ui-docs/components/AnimatedCubeDemo.jsx
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/Header.jsx
  packages/styled-ui-docs/components/TMIcon.jsx
  packages/styled-ui-docs/pages/_document.js
  packages/styled-ui-docs/pages/accordion.mdx
  packages/styled-ui-docs/pages/alert.mdx
  packages/styled-ui-docs/pages/badge.mdx
  packages/styled-ui-docs/pages/button.mdx
  packages/styled-ui-docs/pages/buttonbase.mdx
  packages/styled-ui-docs/pages/buttongroup.mdx
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/icon.mdx
  packages/styled-ui-docs/pages/input.mdx
  packages/styled-ui-docs/pages/inputgroup.mdx
  packages/styled-ui-docs/pages/link.mdx
  packages/styled-ui-docs/pages/menu.mdx
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-docs/pages/pagination.mdx
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/pages/space.mdx
  packages/styled-ui-docs/pages/table.mdx
  packages/styled-ui-docs/pages/tag.mdx
  packages/styled-ui-docs/pages/textarea.mdx
  packages/styled-ui-docs/pages/toast.mdx
  packages/styled-ui-docs/pages/tooltip.mdx
  packages/styled-ui-docs/public/tmicon/fonts/TMicon.eot
  packages/styled-ui-docs/public/tmicon/fonts/TMicon.svg
  packages/styled-ui-docs/public/tmicon/fonts/TMicon.ttf
  packages/styled-ui-docs/public/tmicon/fonts/TMicon.woff
  packages/styled-ui-docs/public/tmicon/fonts/TMicon.woff2
  packages/styled-ui-docs/public/tmicon/tmicon-font.css
Labels: 📝 documentation, 🚀 feature (enhancement)

#213 chore: update yarn.lock file
  yarn.lock
Labels: 🧱 build (ci/cd)

#217 feat: gradient color palette update and add blindness color palette
  packages/styled-ui-docs/components/ColorPalette.jsx
  packages/styled-ui-docs/pages/colors.mdx
  packages/styled-ui-theme/src/color-palette.js
Labels: 🔎 review required

#211 refactor: Tag component
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/Tag/styles.js
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/EditableTag.jsx
  packages/styled-ui-docs/components/SelectableTable.jsx
  packages/styled-ui-docs/pages/tag.mdx
Labels: 📝 documentation

#218 fix: Icon can't be hovered
  packages/react-styled-ui/src/SVGIcon/index.js
  packages/styled-ui-docs/pages/icon.mdx
  packages/styled-ui-docs/pages/svgicon.mdx
Labels: 🐞 bug, 🔎 review required

#219 fix: checkbox icons
  packages/react-styled-ui/src/Checkbox/IconCheck.js
  packages/react-styled-ui/src/Checkbox/IconMinus.js
  packages/react-styled-ui/src/Checkbox/index.js
Labels: 🐞 bug

#212 feat: popover follow mouse cursor
  packages/react-styled-ui/src/Popover/Popover.js
  packages/react-styled-ui/src/Popover/PopoverContent.js
  packages/react-styled-ui/src/Popover/PopoverTrigger.js
  packages/styled-ui-docs/pages/popover.mdx
Labels: 🔎 review required, 🚀 feature (enhancement)

#221 feat: add tonic icon and rename Branding
  README.md
  packages/styled-ui-docs/components/Header.jsx
  packages/styled-ui-docs/pages/getting-started.mdx
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/public/images/tonic.png
Labels: 📝 documentation, 🔎 review required
