Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-03, with the labels that each got.

#60 feat(theme): implement theme page of styled UI
  packages/react-styled-core/src/shared/config.js
  packages/styled-docs/components/ColorPalette.jsx
  packages/styled-docs/components/ThemeParser.jsx
  packages/styled-docs/pages/theme.mdx
Labels: 🚀 feature (enhancement)

#57 feat: add Checkbox and ControlBox components
  packages/react-styled-core/src/Button/index.js
  packages/react-styled-core/src/Button/styles.js
  packages/react-styled-core/src/Checkbox/index.js
  packages/react-styled-core/src/Checkbox/styles.js
  packages/react-styled-core/src/ControlBox/index.js
  packages/react-styled-core/src/VisuallyHidden/index.js
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/theme/icons.js
  packages/styled-docs/pages/checkbox.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#58 refactor: remove orphaned props from shadows
  packages/styled-docs/pages/stack.mdx
  packages/styled-theme/src/base.js
Labels: 👷 refactor (improvement), 🔎 review required, 🛑 breaking change

#62 docs: add getting start docs
  packages/react-styled-core/package.json
  packages/styled-docs/pages/_app.js
  packages/styled-docs/pages/getting-started.mdx
Labels: 📝 documentation

#63 feat: add CheckboxGroup component
  packages/react-styled-core/src/CheckboxGroup/index.js
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/utils/autoId.js
  packages/react-styled-core/src/utils/useIsomorphicLayoutEffect.js
  packages/styled-docs/pages/checkboxgroup.mdx
  packages/styled-docs/pages/controlbox.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#64 build: add env variable for demo page routing
  packages/styled-docs/.env.production
  packages/styled-docs/next.config.js
  packages/styled-docs/package.json
  packages/styled-docs/pages/_app.js
Labels: 🐞 bug

#65 feat: add Radio and RadioGroup components
  packages/react-styled-core/package.json
  packages/react-styled-core/src/GroupContext/index.js
  packages/react-styled-core/src/Radio/index.js
  packages/react-styled-core/src/Radio/styles.js
  packages/react-styled-core/src/RadioGroup/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/radio.mdx
  packages/styled-docs/pages/radiogroup.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#61 docs: add color mode docs
  commitlint.config.js
  package.json
  packages/react-styled-core/src/DarkMode/index.js
  packages/react-styled-core/src/LightMode/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/components/AnimatedCube.jsx
  packages/styled-docs/components/Cube.jsx
  packages/styled-docs/pages/box.mdx
  packages/styled-docs/pages/color-mode.mdx
  packages/styled-docs/pages/controlbox.mdx
  packages/styled-theme/src/base.js
Labels: 📝 documentation

#66 build: enhance build scripts and bump dependencies
  lerna.json
  package.json
  packages/react-styled-core/package.json
  packages/styled-docs/next.config.js
  packages/styled-docs/package.json
  packages/styled-theme/package.json
  scripts/rollup.config.js
Labels: 👷 refactor (improvement), 🧱 build (ci/cd)

#68 refactor: wrap children with a context provider in CheckboxGroup component
  packages/react-styled-core/src/Checkbox/index.js
  packages/react-styled-core/src/CheckboxGroup/index.js
  packages/styled-docs/pages/checkboxgroup.mdx
  packages/styled-docs/pages/radiogroup.mdx
Labels: 👷 refactor (improvement)

#70 docs: refactor theme page to a single section
  packages/styled-docs/components/SideNav.jsx
  packages/styled-docs/pages/borders.mdx
  packages/styled-docs/pages/breakpoints.mdx
  packages/styled-docs/pages/colors.mdx
  packages/styled-docs/pages/positions.mdx
  packages/styled-docs/pages/shadows.mdx
  packages/styled-docs/pages/sizes.mdx
  packages/styled-docs/pages/spacing.mdx
  packages/styled-docs/pages/theme.mdx
  packages/styled-docs/pages/typography.mdx
  packages/styled-docs/shared/themes.js
  packages/styled-theme/src/base.js
Labels: 👷 refactor (improvement), 📝 documentation

#71 docs: refactor pages and components
  packages/react-styled-core/src/shared/config.js
  packages/styled-docs/components/AnimatedCube.jsx
  packages/styled-docs/components/AnimatedCubeDemo.jsx
  packages/styled-docs/components/CodeBlock.jsx
  packages/styled-docs/components/Cube.jsx
  packages/styled-docs/components/DocsIcon.jsx
  packages/styled-docs/components/Header.jsx
  packages/styled-docs/components/TMIcon.jsx
  packages/styled-docs/pages/box.mdx
  packages/styled-docs/pages/svgicon.mdx
  packages/styled-docs/public/images/Trend-Micro-Logo.svg
Labels: 👷 refactor (improvement), 📝 documentation, 🚀 feature (enhancement)

#69 feat(transition): Fade component
  packages/react-styled-core/package.json
  packages/react-styled-core/src/Fade/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/fade.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#74 feat(testing): jest integration
  .eslintrc.js
  .travis.yml
  package.json
  packages/react-styled-core/babel.config.js
  packages/react-styled-core/package.json
  packages/react-styled-core/src/shared/config.js
  packages/react-styled-core/test/styled-system-defaults.js
  packages/styled-docs/package.json
  packages/styled-theme/babel.config.js
  packages/styled-theme/package.json
Labels: 🚀 feature (enhancement)

#75 feat: Input component
  packages/react-styled-core/src/Input/index.js
  packages/react-styled-core/src/Input/styles.js
  packages/react-styled-core/src/Input/useInputStyle.js
  packages/react-styled-core/src/PseudoBox/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/buttongroup.mdx
  packages/styled-docs/pages/checkbox.mdx
  packages/styled-docs/pages/checkboxgroup.mdx
  packages/styled-docs/pages/input.mdx
  packages/styled-docs/pages/radio.mdx
  packages/styled-docs/pages/radiogroup.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#76 refactor: enhance button component
  packages/react-styled-core/src/Button/index.js
  packages/react-styled-core/src/Button/styles.js
  packages/react-styled-core/src/ButtonGroup/index.js
  packages/react-styled-core/src/PseudoBox/index.js
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/buttongroup.mdx
Labels: 👷 refactor (improvement)

#78 feat: add FlatButton component
  packages/react-styled-core/src/Button/styles.js
  packages/react-styled-core/src/FlatButton/index.js
  packages/react-styled-core/src/FlatButton/styles.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/flatbutton.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#77 feat: alert component
  packages/react-styled-core/src/Alert/index.js
  packages/react-styled-core/src/Alert/styles.js
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/theme/icons.js
  packages/styled-docs/pages/accordion.mdx
  packages/styled-docs/pages/alert.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#79 feat: implement tooltip component
  packages/react-styled-core/package.json
  packages/react-styled-core/src/Popper/index.js
  packages/react-styled-core/src/Popper/styles.js
  packages/react-styled-core/src/Portal/index.js
  packages/react-styled-core/src/Tooltip/index.js
  packages/react-styled-core/src/Tooltip/styles.js
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/useDisclosure/index.js
  packages/react-styled-core/src/utils/setRef.js
  packages/react-styled-core/src/utils/useEnhancedEffect.js
  packages/react-styled-core/src/utils/useForkRef.js
  packages/styled-docs/pages/tooltip.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#83 feat: add `size` prop to `Heading` and `Text` components
  packages/react-styled-core/src/.DS_Store
  packages/react-styled-core/src/Heading/index.js
  packages/react-styled-core/src/Text/index.js
  packages/styled-docs/pages/badge.mdx
  packages/styled-docs/pages/heading.mdx
  packages/styled-docs/pages/input.mdx
  packages/styled-docs/pages/text.mdx
Labels: 🚀 feature (enhancement)

#82 refactor: improvement something for Checkbox and Radio
  packages/react-styled-core/src/Checkbox/index.js
  packages/react-styled-core/src/Checkbox/styles.js
  packages/react-styled-core/src/CheckboxGroup/context.js
  packages/react-styled-core/src/CheckboxGroup/index.js
  packages/react-styled-core/src/GroupContext/index.js
  packages/react-styled-core/src/Radio/index.js
  packages/react-styled-core/src/Radio/styles.js
  packages/react-styled-core/src/RadioGroup/context.js
  packages/react-styled-core/src/RadioGroup/index.js
Labels: 👷 refactor (improvement)

#85 docs: update Input and InputGroup examples
  packages/react-styled-core/src/Input/styles.js
  packages/react-styled-core/src/InputGroupAddon/styles.js
  packages/react-styled-core/src/InputLabel/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/input.mdx
  packages/styled-docs/pages/inputgroup.mdx
Labels: 📝 documentation, 🚀 feature (enhancement)

#86 feat: InputBase component
  packages/react-styled-core/src/ButtonBase/index.js
  packages/react-styled-core/src/ButtonBase/styles.js
  packages/react-styled-core/src/Input/index.js
  packages/react-styled-core/src/Input/styles.js
  packages/react-styled-core/src/Input/useInputStyle.js
  packages/react-styled-core/src/InputBase/index.js
  packages/react-styled-core/src/InputBase/styles.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/buttonbase.mdx
  packages/styled-docs/pages/input.mdx
  packages/styled-docs/pages/inputbase.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#84 feat: Spinner component
  packages/react-styled-core/src/Spinner/index.js
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/shared/config.js
  packages/react-styled-core/src/utils/ensure-type.js
  packages/styled-docs/pages/spinner.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)
