Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-09, with the labels that each got.

#222 docs: changed branding image and added favicon
  packages/styled-ui-docs/components/Header.jsx
  packages/styled-ui-docs/pages/_document.js
  packages/styled-ui-docs/pages/colors.mdx
  packages/styled-ui-docs/public/favicon.ico
  packages/styled-ui-docs/public/images/tonic-logo-dark.svg
  packages/styled-ui-docs/public/images/tonic-logo-light.svg
  packages/styled-ui-docs/public/images/tonic.png
  packages/styled-ui-docs/public/tonic-favicon-dark.ico
  packages/styled-ui-theme/src/color-palette.js
Labels: 📝 documentation, 🔎 review required

#220 breaking: drop out rollup module bundler for context sharing between named imports and default imports
  package.json
  packages/react-styled-ui/index.js
  packages/react-styled-ui/package.json
  packages/styled-ui-theme/index.js
  packages/styled-ui-theme/package.json
  scripts/rollup.config.js
  yarn.lock
Labels: 🔎 review required, 🛑 breaking change

#225 feat: add Option and OptionGroup components
  packages/react-styled-ui/src/Select/Option.js
  packages/react-styled-ui/src/Select/OptionGroup.js
  packages/react-styled-ui/src/Select/Select.js
  packages/react-styled-ui/src/Select/index.js
  packages/react-styled-ui/src/Select/styles.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/pages/input.mdx
  packages/styled-ui-docs/pages/select.mdx
Labels: 🚀 feature (enhancement)

#226 feat: add a property for arrow position handling
  packages/react-styled-ui/src/Popover/Popover.js
  packages/react-styled-ui/src/Popover/PopoverContent.js
  packages/react-styled-ui/src/Popper/index.js
  packages/react-styled-ui/src/Popper/styles.js
  packages/react-styled-ui/src/Tooltip/index.js
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/pages/tooltip.mdx
Labels: 🔎 review required, 🚀 feature (enhancement)

#228 doc: update docs
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/accordion.mdx
  packages/styled-ui-docs/pages/checkbox.mdx
  packages/styled-ui-docs/pages/divider.mdx
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/inputgroup.mdx
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-docs/pages/pagination.mdx
  packages/styled-ui-docs/pages/transition.mdx
Labels: 📝 documentation

#229 feat: add displayName to each component
  packages/react-styled-ui/src/Accordion/index.js
  packages/react-styled-ui/src/ButtonGroup/index.js
  packages/react-styled-ui/src/CSSBaseline/index.js
  packages/react-styled-ui/src/Checkbox/IconCheck.js
  packages/react-styled-ui/src/Checkbox/IconMinus.js
  packages/react-styled-ui/src/CheckboxGroup/index.js
  packages/react-styled-ui/src/ColorModeProvider/index.js
  packages/react-styled-ui/src/DarkMode/index.js
  packages/react-styled-ui/src/Divider/index.js
  packages/react-styled-ui/src/LightMode/index.js
  packages/react-styled-ui/src/Menu/Menu.js
  packages/react-styled-ui/src/Menu/MenuList.js
  packages/react-styled-ui/src/Pagination/index.js
  packages/react-styled-ui/src/Popper/index.js
  packages/react-styled-ui/src/SearchInput/index.js
  packages/react-styled-ui/src/Skeleton/index.js
  packages/react-styled-ui/src/Stack/index.js
  packages/react-styled-ui/src/ThemeProvider/index.js
  packages/react-styled-ui/src/Tooltip/index.js
  packages/react-styled-ui/src/Transition/index.js
Labels: 🚀 feature (enhancement)

#232 refactor: use orientation prop to replace vertical prop
  packages/react-styled-ui/src/Button/index.js
  packages/react-styled-ui/src/ButtonGroup/index.js
  packages/react-styled-ui/src/Divider/index.js
  packages/styled-ui-docs/pages/buttongroup.mdx
  packages/styled-ui-docs/pages/divider.mdx
  packages/styled-ui-docs/pages/inputgroup.mdx
  packages/styled-ui-docs/pages/pagination.mdx
Labels: 👷 refactor (improvement)

#235 docs: add pixel documentation for fontsize and lineheight
  packages/styled-ui-docs/pages/typography.mdx
Labels: 📝 documentation

#237 fix: fix duplicate event for Checkbox and Radio
  packages/react-styled-ui/src/Checkbox/index.js
  packages/react-styled-ui/src/Radio/index.js
Labels: 🐞 bug
