Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-11, with the labels that each got.

#248 fix: disabled FocusLock by adding a new attribute ensureFocus
  packages/react-styled-ui/src/Drawer/Drawer.js
  packages/react-styled-ui/src/Modal/Modal.js
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/modal.mdx
Labels: 👷 refactor (improvement), 🔎 review required

#253 fix(SSR): change the unreliable pseudo class ":first-child" to ":first-of-type"
  packages/react-styled-ui/src/Checkbox/styles.js
  packages/react-styled-ui/src/Drawer/DrawerBody.js
  packages/react-styled-ui/src/Drawer/DrawerContent.js
  packages/react-styled-ui/src/Drawer/DrawerFooter.js
  packages/react-styled-ui/src/Drawer/DrawerHeader.js
  packages/react-styled-ui/src/Drawer/styles.js
  packages/react-styled-ui/src/Input/styles.js
  packages/react-styled-ui/src/InputGroupAppend/styles.js
  packages/react-styled-ui/src/InputGroupPrepend/styles.js
  packages/react-styled-ui/src/Modal/ModalBody.js
  packages/react-styled-ui/src/Modal/ModalContent.js
  packages/react-styled-ui/src/Modal/ModalFooter.js
  packages/react-styled-ui/src/Modal/ModalHeader.js
  packages/react-styled-ui/src/Modal/styles.js
  packages/styled-ui-docs/components/Main.jsx
  packages/styled-ui-docs/pages/buttongroup.mdx
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/input.mdx
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-docs/pages/pagination.mdx
  packages/styled-ui-docs/pages/transition.mdx
Labels: 👷 refactor (improvement)

#256 Update TMIcon to 1.7
  packages/react-styled-ui/src/Icon/tmIconMap.js
Labels: 🎉 feature (enhancement)
