Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-05, with the labels that each got.

#118 feat: add second color on spinner
  packages/react-styled-ui/src/Spinner/index.js
  packages/styled-ui-docs/pages/badge.mdx
  packages/styled-ui-docs/pages/spinner.mdx
Labels: 🏗️ work in progress, 💬 discussion, 🔎 review required

#125 fix: set `line-height` to 1 for base components and TMIcon component
  packages/react-styled-ui/src/ButtonBase/styles.js
  packages/react-styled-ui/src/Input/styles.js
  packages/react-styled-ui/src/InputBase/styles.js
  packages/styled-ui-docs/components/TMIcon.jsx
  packages/styled-ui-docs/pages/inputbase.mdx
Labels: 🐞 bug

#126 fix: missing uuid dependency in react-styled-ui
  packages/react-styled-ui/src/Accordion/index.js
  packages/react-styled-ui/src/utils/uniqueid.js
Labels: 🐞 bug

#128 fix: keydown event for PopoverTrigger
  packages/react-styled-ui/src/Popover/PopoverTrigger.js
Labels: 🐞 bug

#130 fix: Link component style
  packages/react-styled-ui/src/Link/index.js
  packages/styled-ui-docs/pages/link.mdx
Labels: 🐞 bug, 📝 documentation

#124 feat: Modal Component
  packages/react-styled-ui/package.json
  packages/react-styled-ui/src/Modal/Modal.js
  packages/react-styled-ui/src/Modal/ModalBody.js
  packages/react-styled-ui/src/Modal/ModalCloseButton.js
  packages/react-styled-ui/src/Modal/ModalContent.js
  packages/react-styled-ui/src/Modal/ModalFooter.js
  packages/react-styled-ui/src/Modal/ModalHeader.js
  packages/react-styled-ui/src/Modal/ModalOverlay.js
  packages/react-styled-ui/src/Modal/context.js
  packages/react-styled-ui/src/Modal/index.js
  packages/react-styled-ui/src/Modal/styles.js
  packages/react-styled-ui/src/index.js
  packages/react-styled-ui/src/theme/icons.js
  packages/react-styled-ui/src/utils/getFocusables.js
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/package.json
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-theme/src/base.js
Labels: 🚀 feature (enhancement)

#135 refactor: the `useToast` Hook should return object type for future expansion (close #129)
  packages/react-styled-ui/src/useToast/index.js
  packages/styled-ui-docs/pages/alerttoast.mdx
  packages/styled-ui-docs/pages/toast.mdx
  packages/styled-ui-docs/pages/usetoast.mdx
Labels: 👷 refactor (improvement)

#136 docs: edit getting start and color modes
  packages/styled-ui-docs/pages/color-modes.mdx
  packages/styled-ui-docs/pages/getting-started.mdx
Labels: 🚀 feature (enhancement)

#137 docs: update docs for Table
  packages/styled-ui-docs/pages/table.mdx
Labels: 🐞 bug, 📝 documentation

#140 docs: add the example for full width table
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/package.json
  packages/styled-ui-docs/pages/table.mdx
Labels: 📝 documentation
