Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-04, with the labels that each got.

#95 feat: create review site deployment for each pull request
  .travis.yml
Labels: 🚀 feature (enhancement), 🧱 build (ci/cd)

#96 build: change personal access token owner and change the path for PR demo site
  .travis.yml
Labels: 👷 refactor (improvement), 🧱 build (ci/cd)

#97 ci: create the commit message using the commit SHA of the HEAD commit of the PR
  .travis.yml
Labels: 🧱 build (ci/cd)

#93 refactor: improve tooltip variantColor
  packages/react-styled-core/src/Popper/index.js
  packages/react-styled-core/src/Popper/styles.js
  packages/react-styled-core/src/Tooltip/index.js
  packages/react-styled-core/src/Tooltip/styles.js
  packages/styled-docs/pages/tooltip.mdx
Labels: 👷 refactor (improvement)

#98 docs: use consistent conventions for writing documentation
  packages/styled-docs/pages/accordion.mdx
  packages/styled-docs/pages/alert.mdx
  packages/styled-docs/pages/badge.mdx
  packages/styled-docs/pages/box.mdx
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/buttonbase.mdx
  packages/styled-docs/pages/buttongroup.mdx
  packages/styled-docs/pages/checkbox.mdx
  packages/styled-docs/pages/checkboxgroup.mdx
  packages/styled-docs/pages/collapse.mdx
  packages/styled-docs/pages/controlbox.mdx
  packages/styled-docs/pages/cssbaseline.mdx
  packages/styled-docs/pages/fade.mdx
  packages/styled-docs/pages/flatbutton.mdx
  packages/styled-docs/pages/flex.mdx
  packages/styled-docs/pages/grid.mdx
  packages/styled-docs/pages/heading.mdx
  packages/styled-docs/pages/input.mdx
  packages/styled-docs/pages/inputbase.mdx
  packages/styled-docs/pages/inputgroup.mdx
  packages/styled-docs/pages/link.mdx
  packages/styled-docs/pages/pseudobox.mdx
  packages/styled-docs/pages/radio.mdx
  packages/styled-docs/pages/radiogroup.mdx
  packages/styled-docs/pages/spinner.mdx
  packages/styled-docs/pages/stack.mdx
  packages/styled-docs/pages/svgicon.mdx
  packages/styled-docs/pages/text.mdx
  packages/styled-docs/pages/textarea.mdx
  packages/styled-docs/pages/textlabel.mdx
  packages/styled-docs/pages/tooltip.mdx
Labels: 👷 refactor (improvement), 📝 documentation

#89 feat: toggle switch component
  packages/react-styled-core/src/ControlBox/index.js
  packages/react-styled-core/src/Image/index.js
  packages/react-styled-core/src/ThemeProvider/index.js
  packages/react-styled-core/src/ToggleSwitch/index.js
  packages/react-styled-core/src/ToggleSwitch/styles.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/toggleswitch.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#90 refactor: remove default value of context from CheckboxGroup and RadioGroup
  packages/react-styled-core/src/Checkbox/index.js
  packages/react-styled-core/src/CheckboxGroup/context.js
  packages/react-styled-core/src/CheckboxGroup/index.js
  packages/react-styled-core/src/Radio/index.js
  packages/react-styled-core/src/RadioGroup/context.js
  packages/react-styled-core/src/RadioGroup/index.js
  packages/react-styled-core/src/utils/ensure-type.js
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/checkbox.mdx
  packages/styled-docs/pages/checkboxgroup.mdx
  packages/styled-docs/pages/flatbutton.mdx
  packages/styled-docs/pages/radio.mdx
  packages/styled-docs/pages/radiogroup.mdx
Labels: 👷 refactor (improvement)

#88 refactor: `cloneElement` was removed in favor of using React Context API for ButtonGroup
  packages/react-styled-core/src/Button/index.js
  packages/react-styled-core/src/Button/styles.js
  packages/react-styled-core/src/ButtonGroup/context.js
  packages/react-styled-core/src/ButtonGroup/index.js
  packages/styled-docs/pages/buttongroup.mdx
Labels: 👷 refactor (improvement)

#99 docs: update sizes and spacing theme example
  packages/styled-docs/pages/sizes.mdx
  packages/styled-docs/pages/spacing.mdx
Labels: 📝 documentation

#100 refactor(styled-system): deprecate the `size` prop in the layout utility
  packages/react-styled-core/package.json
  packages/react-styled-core/src/Alert/index.js
  packages/react-styled-core/src/Box/index.js
  packages/react-styled-core/src/Checkbox/index.js
  packages/react-styled-core/src/Radio/index.js
  packages/react-styled-core/src/SVGIcon/index.js
  packages/react-styled-core/src/shared/styled-system/config.js
  packages/react-styled-core/src/shared/styled-system/layout.js
  packages/react-styled-core/src/shared/styled-system/utils.js
  packages/react-styled-core/src/shared/styled-system/utils.test.js
  packages/react-styled-core/test/styled-system/defaults.js
  packages/react-styled-core/test/styled-system/layout.js
  packages/styled-theme/package.json
Labels: 👷 refactor (improvement)

#102 feat: Toast Component
  packages/react-styled-core/package.json
  packages/react-styled-core/src/ActionButton/index.js
  packages/react-styled-core/src/Alert/index.js
  packages/react-styled-core/src/Alert/styles.js
  packages/react-styled-core/src/Toast/index.js
  packages/react-styled-core/src/Toast/styles.js
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/theme/icons.js
  packages/styled-docs/pages/toast.mdx
  packages/styled-docs/shared/components.js
Labels: 🚀 feature (enhancement)

#104 fix: use size instead of width and height for Icon
  packages/react-styled-core/src/Alert/index.js
  packages/react-styled-core/src/Checkbox/index.js
  packages/react-styled-core/src/Checkbox/styles.js
  packages/react-styled-core/src/Toast/index.js
Labels: 🐞 bug

#103 fix: remove size prop
  .travis.yml
  packages/styled-docs/components/ColorPalette.jsx
  packages/styled-docs/pages/borders.mdx
  packages/styled-docs/pages/colors.mdx
  packages/styled-docs/pages/controlbox.mdx
  packages/styled-docs/pages/spacing.mdx
Labels: 🐞 bug

#105 docs: add a "building blocks" section to the side navigation
  packages/react-styled-core/src/DarkMode/index.js
  packages/react-styled-core/src/LightMode/index.js
  packages/styled-docs/components/SideNav.jsx
  packages/styled-docs/components/nav-links.js
  packages/styled-docs/pages/color-mode.mdx
  packages/styled-docs/pages/color-modes.mdx
  packages/styled-docs/pages/controlbox.mdx
  packages/styled-docs/shared/themes.js
Labels: 📝 documentation

#107 Component/link
  packages/react-styled-core/src/Link/index.js
  packages/styled-docs/pages/link.mdx
Labels: 👷 refactor (improvement)

#121 docs: refine documentation for the ButtonBase component
  packages/styled-ui-docs/pages/buttonbase.mdx
Labels: 📝 documentation

#120 docs: refine documentation for toasts
  packages/react-styled-ui/src/AlertToast/styles.js
  packages/react-styled-ui/src/Toast/styles.js
  packages/react-styled-ui/src/useToast/index.js
  packages/styled-ui-docs/pages/alerttoast.mdx
  packages/styled-ui-docs/pages/text.mdx
  packages/styled-ui-docs/pages/toast.mdx
  packages/styled-ui-docs/pages/usetoast.mdx
Labels: 👷 refactor (improvement), 📝 documentation

#116 feat: popover component
  packages/react-styled-ui/src/Popover/Popover.js
  packages/react-styled-ui/src/Popover/PopoverBody.js
  packages/react-styled-ui/src/Popover/PopoverContent.js
  packages/react-styled-ui/src/Popover/PopoverFooter.js
  packages/react-styled-ui/src/Popover/PopoverHeader.js
  packages/react-styled-ui/src/Popover/PopoverTrigger.js
  packages/react-styled-ui/src/Popover/context.js
  packages/react-styled-ui/src/Popover/index.js
  packages/react-styled-ui/src/Popover/styles.js
  packages/react-styled-ui/src/index.js
  packages/react-styled-ui/src/utils/wrapEvent.js
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/popover.mdx
Labels: 🚀 feature (enhancement)

#119 feat: add Table component
  packages/react-styled-ui/src/Table/Table.js
  packages/react-styled-ui/src/Table/TableBody.js
  packages/react-styled-ui/src/Table/TableCell.js
  packages/react-styled-ui/src/Table/TableHeader.js
  packages/react-styled-ui/src/Table/TableHeaderCell.js
  packages/react-styled-ui/src/Table/TableHeaderRow.js
  packages/react-styled-ui/src/Table/TableRow.js
  packages/react-styled-ui/src/Table/context.js
  packages/react-styled-ui/src/Table/index.js
  packages/react-styled-ui/src/Table/styles.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/SelectableTable.jsx
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/package.json
  packages/styled-ui-docs/pages/table.mdx
Labels: 🚀 feature (enhancement)
