Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-10, with the labels that each got.

#240 docs: change the examples color of spacing, sizes, flex, and grid
  packages/styled-ui-docs/pages/flex.mdx
  packages/styled-ui-docs/pages/grid.mdx
  packages/styled-ui-docs/pages/sizes.mdx
  packages/styled-ui-docs/pages/spacing.mdx
  packages/styled-ui-docs/pages/typography.mdx
Labels: 📝 documentation, 🔎 review required

#241 docs: add the example for movable table
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/package.json
  packages/styled-ui-docs/pages/table.mdx
Labels: 📝 documentation, 🔎 review required

#245 fix: remove the Heading component and document
  packages/react-styled-ui/src/Heading/index.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/components/MDXComponents.jsx
  packages/styled-ui-docs/components/SideNav.jsx
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/alert.mdx
  packages/styled-ui-docs/pages/heading.mdx
  packages/styled-ui-docs/pages/skeleton.mdx
  packages/styled-ui-docs/pages/text.mdx
  packages/styled-ui-docs/pages/toast.mdx
Labels: 📝 documentation, 🛑 breaking change

#244 docs: add collapse code block
  packages/styled-ui-docs/components/CodeBlock.jsx
Labels: 🔎 review required, 🚀 feature (enhancement)

#246 fix: Icon component fill property
  packages/react-styled-ui/src/Icon/tmIconSvgMap.js
  packages/react-styled-ui/src/Link/index.js
  packages/react-styled-ui/src/SVGIcon/index.js
Labels: 🐞 bug, 🔎 review required
