Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-02, with the labels that each got.

#25 feat: refine MDX document layout
  packages/styled-docs/components/MDXComponents.jsx
  packages/styled-docs/components/Main.jsx
  packages/styled-docs/pages/_app.js
  packages/styled-docs/pages/_error.js
Labels: 📚 documentation

#29 feat: stack component
  packages/react-styled-core/src/Stack/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/flex.mdx
  packages/styled-docs/pages/stack.mdx
  packages/styled-docs/shared/components.js
Labels: ⭐ feature (enhancement)

#27 feat: grid component
  packages/react-styled-core/src/Grid/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/_app.js
  packages/styled-docs/pages/flex.mdx
  packages/styled-docs/pages/grid.mdx
Labels: ⭐ feature (enhancement)

#32 docs: add the props block of the link component
  packages/styled-docs/pages/link.mdx
Labels: 📚 documentation

#33 feat: Space component
  packages/react-styled-core/src/Space/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/components/TMIcon.jsx
  packages/styled-docs/pages/space.mdx
  packages/styled-docs/shared/components.js
Labels: ⭐ feature (enhancement)

#37 chore: to dark theme on demo page
  packages/styled-docs/pages/_app.js
Labels: 👷 improvement, 📚 documentation

#38 feat: Image component
  packages/styled-docs/components/CodeBlock.jsx
  packages/styled-docs/pages/image.mdx
Labels: ⭐ feature (enhancement)

#35 feat: Text component
  packages/styled-docs/pages/badge.mdx
  packages/styled-docs/pages/box.mdx
  packages/styled-docs/pages/collapse.mdx
  packages/styled-docs/pages/flex.mdx
  packages/styled-docs/pages/stack.mdx
  packages/styled-docs/pages/text.mdx
  packages/styled-theme/src/base.js
Labels: ⭐ feature (enhancement)

#36 fix: dark mode in accordion
  packages/react-styled-core/src/Accordion/index.js
  packages/react-styled-core/src/CSSBaseline/base-css.js
  packages/styled-docs/pages/accordion.mdx
Labels: 🐛 bug

#39 feat: CSSBaseline component
  packages/styled-docs/pages/cssbaseline.mdx
Labels: ⭐ feature (enhancement)

#40 feat: copy button on codeBlock
  packages/react-styled-core/src/index.js
  packages/react-styled-core/src/useClipboard/index.js
  packages/styled-docs/components/CodeBlock.jsx
Labels: 👷 improvement

#42 improvement: remove variant from Link and update docs
  packages/react-styled-core/src/Link/index.js
  packages/styled-docs/pages/link.mdx
Labels: 👷 improvement

#44 feat: ButtonBase component
  packages/react-styled-core/src/ButtonBase/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/buttonbase.mdx
  packages/styled-docs/shared/components.js
Labels: ⭐ feature (enhancement)

#43 docs: update wordings in docs
  packages/styled-docs/components/SideNav.jsx
  packages/styled-docs/pages/badge.mdx
  packages/styled-docs/pages/box.mdx
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/collapse.mdx
  packages/styled-docs/pages/contributing.mdx
  packages/styled-docs/pages/flex.mdx
  packages/styled-docs/pages/image.mdx
  packages/styled-docs/pages/link.mdx
  packages/styled-docs/pages/stack.mdx
  packages/styled-docs/pages/svgicon.mdx
  packages/styled-docs/shared/components.js
Labels: 📚 documentation

#41 feat: PseudoBox component
  packages/react-styled-core/src/PseudoBox/index.js
  packages/styled-docs/pages/pseudobox.mdx
Labels: ⭐ feature (enhancement)

#46 fix: side header component zindex
  packages/styled-docs/components/Header.jsx
  packages/styled-docs/pages/_app.js
Labels: 🐛 bug

#47 refactor: Accordion component
  packages/react-styled-core/src/Accordion/index.js
  packages/react-styled-core/src/theme/icons.js
  packages/react-styled-core/src/theme/index.js
  packages/styled-docs/pages/accordion.mdx
  packages/styled-docs/pages/badge.mdx
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/buttonbase.mdx
  packages/styled-docs/pages/collapse.mdx
  packages/styled-docs/pages/icon.mdx
  packages/styled-docs/pages/image.mdx
  packages/styled-docs/pages/index.mdx
  packages/styled-docs/pages/link.mdx
  packages/styled-docs/pages/stack.mdx
  packages/styled-docs/pages/svgicon.mdx
  packages/styled-docs/pages/text.mdx
Labels: 👷 refactor (improvement)

#34 feat: add ButtonGroup component
  packages/react-styled-core/src/Button/index.js
  packages/react-styled-core/src/Button/styles.js
  packages/react-styled-core/src/ButtonGroup/index.js
  packages/react-styled-core/src/CSSBaseline/base-css.js
  packages/react-styled-core/src/PseudoBox/index.js
  packages/react-styled-core/src/index.js
  packages/styled-docs/pages/button.mdx
  packages/styled-docs/pages/buttongroup.mdx
  packages/styled-docs/shared/components.js
Labels: ⭐ feature (enhancement)

#48 feat: Heading component
  packages/react-styled-core/src/Heading/index.js
  packages/styled-docs/pages/heading.mdx
  packages/styled-docs/pages/link.mdx
  packages/styled-docs/pages/pseudobox.mdx
  packages/styled-docs/shared/components.js
  packages/styled-theme/src/base.js
Labels: ⭐ feature (enhancement)

#53 refactor: remove orphaned packages and enhance build scripts
  .eslintignore
  .huskyrc.js
  .travis.yml
  package.json
  packages/react-styled-core/.eslintignore
  packages/react-styled-core/.storybook/config.js
  packages/react-styled-core/.storybook/presets.js
  packages/react-styled-core/.storybook/webpack.config.js
  packages/react-styled-core/package.json
  packages/styled-docs/.eslintignore
  packages/styled-docs/package.json
  packages/styled-theme/.eslintignore
  packages/styled-theme/package.json
Labels: 👷 refactor (improvement)
