Repository trendmicro-frontend/tonic-ui, pull requests merged in 2020-06, with the labels that each got.

#141 feat: add SearchInput component
  packages/react-styled-ui/src/SearchInput/index.js
  packages/react-styled-ui/src/SearchInput/split-props.js
  packages/react-styled-ui/src/index.js
  packages/react-styled-ui/src/theme/icons.js
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/input.mdx
  packages/styled-ui-docs/pages/searchinput.mdx
Labels: 🚀 feature (enhancement)

#149 feat: add Skeleton component
  packages/react-styled-ui/package.json
  packages/react-styled-ui/src/FlatButton/index.js
  packages/react-styled-ui/src/Skeleton/index.js
  packages/react-styled-ui/src/Skeleton/styles.js
  packages/react-styled-ui/src/ToggleSwitch/index.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/package.json
  packages/styled-ui-docs/pages/skeleton.mdx
  packages/styled-ui-theme/package.json
Labels: 🚀 feature (enhancement)

#134 feat: add Tag component
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/Tag/styles.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/tag.mdx
Labels: 🚀 feature (enhancement)

#152 fix: fix incorrect close icon
  packages/react-styled-ui/src/theme/icons.js
Labels: 🐞 bug

#154 fix(skeleton): fix incorrect skeleton colors for dark and light mode
  packages/react-styled-ui/src/Skeleton/styles.js
Labels: 🐞 bug

#156 fix: change popover and tooltip style
  packages/react-styled-ui/src/Icon/index.js
  packages/react-styled-ui/src/Popover/PopoverTrigger.js
  packages/react-styled-ui/src/Tooltip/styles.js
  packages/styled-ui-docs/components/TMIcon.jsx
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/pages/tooltip.mdx
Labels: 👷 refactor (improvement), 📝 documentation

#159 docs: set default font-size and line-height to the body
  packages/styled-ui-docs/pages/_app.js
  packages/styled-ui-docs/pages/getting-started.mdx
Labels: 📝 documentation

#160 refactor(modal): restrict minimum and maximum height only when size is one of xs, sm, md, lg, xl
  packages/react-styled-ui/src/Modal/styles.js
Labels: 👷 refactor (improvement)

#163 feat: menu component
  packages/react-styled-ui/src/Menu/Menu.js
  packages/react-styled-ui/src/Menu/MenuItem.js
  packages/react-styled-ui/src/Menu/MenuList.js
  packages/react-styled-ui/src/Menu/context.js
  packages/react-styled-ui/src/Menu/index.js
  packages/react-styled-ui/src/Menu/styles.js
  packages/react-styled-ui/src/MenuButton/index.js
  packages/react-styled-ui/src/MenuButton/styles.js
  packages/react-styled-ui/src/Popper/index.js
  packages/react-styled-ui/src/PseudoBox/index.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/pages/menu.mdx
Labels: 🚀 feature (enhancement)
