Repository trendmicro-frontend/tonic-ui, pull requests merged in 2021-11, with the labels that each got.

#362 docs: remove unwanted paragraphs
  packages/styled-ui-docs/pages/accordion.mdx
  packages/styled-ui-docs/pages/alert.mdx
  packages/styled-ui-docs/pages/badge.mdx
  packages/styled-ui-docs/pages/button.mdx
  packages/styled-ui-docs/pages/buttonbase.mdx
  packages/styled-ui-docs/pages/buttongroup.mdx
  packages/styled-ui-docs/pages/checkbox.mdx
  packages/styled-ui-docs/pages/collapse.mdx
  packages/styled-ui-docs/pages/controlbox.mdx
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/fade.mdx
  packages/styled-ui-docs/pages/flatbutton.mdx
  packages/styled-ui-docs/pages/icon.mdx
  packages/styled-ui-docs/pages/image.mdx
  packages/styled-ui-docs/pages/input.mdx
  packages/styled-ui-docs/pages/inputbase.mdx
  packages/styled-ui-docs/pages/inputgroup.mdx
  packages/styled-ui-docs/pages/link.mdx
  packages/styled-ui-docs/pages/linkbutton.mdx
  packages/styled-ui-docs/pages/menu.mdx
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-docs/pages/pagination.mdx
  packages/styled-ui-docs/pages/popover.mdx
  packages/styled-ui-docs/pages/pseudobox.mdx
  packages/styled-ui-docs/pages/radio.mdx
  packages/styled-ui-docs/pages/scrollbar.mdx
  packages/styled-ui-docs/pages/searchinput.mdx
  packages/styled-ui-docs/pages/select.mdx
  packages/styled-ui-docs/pages/skeleton.mdx
  packages/styled-ui-docs/pages/stack.mdx
  packages/styled-ui-docs/pages/svgicon.mdx
  packages/styled-ui-docs/pages/table.mdx
  packages/styled-ui-docs/pages/tabs.mdx
  packages/styled-ui-docs/pages/text.mdx
  packages/styled-ui-docs/pages/textarea.mdx
  packages/styled-ui-docs/pages/textlabel.mdx
  packages/styled-ui-docs/pages/toast.mdx
Labels: 📝 documentation

#363 feat: add `isClosable` shorthand and deprecate the legacy `isCloseButtonVisible` prop
  packages/react-styled-ui/src/Alert/index.js
  packages/react-styled-ui/src/Drawer/Drawer.js
  packages/react-styled-ui/src/Drawer/DrawerContent.js
  packages/react-styled-ui/src/Modal/Modal.js
  packages/react-styled-ui/src/Modal/ModalContent.js
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/Tag/styles.js
  packages/react-styled-ui/src/Toast/index.js
  packages/styled-ui-docs/components/EditableTag.jsx
  packages/styled-ui-docs/pages/alert.mdx
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-docs/pages/tag.mdx
  packages/styled-ui-docs/pages/toast.mdx
Labels: 👷 refactor (improvement)

#368 feat: add new style props for CSS containment and outline modules
  packages/react-styled-ui/src/shared/styled-system/config.js
Labels: 🏗️ work in progress, 🎉 feature (enhancement)

#372 docs: fix RadioGroup's value
  packages/styled-ui-docs/pages/scrollbar.mdx
Labels: 🐛 bug, 📝 documentation

#359 feat: add a variant prop to the Alert component that provides different variants to be chosen
  packages/react-styled-ui/src/Alert/index.js
  packages/react-styled-ui/src/Alert/styles.js
  packages/styled-ui-docs/pages/alert.mdx
  packages/styled-ui-docs/pages/drawer.mdx
  packages/styled-ui-docs/pages/modal.mdx
  packages/styled-ui-docs/pages/toast.mdx
Labels: 🎉 feature (enhancement), 🔎 review required

#371 feat: deprecate `PseudoBox` and replace all `PseudoBox` components with `Box`
  packages/react-styled-ui/src/Accordion/AccordionItem.js
  packages/react-styled-ui/src/Box/index.js
  packages/react-styled-ui/src/ButtonBase/index.js
  packages/react-styled-ui/src/Drawer/DrawerBody.js
  packages/react-styled-ui/src/Drawer/DrawerFooter.js
  packages/react-styled-ui/src/Drawer/DrawerHeader.js
  packages/react-styled-ui/src/InputBase/index.js
  packages/react-styled-ui/src/InputGroup/index.js
  packages/react-styled-ui/src/Link/index.js
  packages/react-styled-ui/src/Menu/MenuItem.js
  packages/react-styled-ui/src/MenuButton/index.js
  packages/react-styled-ui/src/Modal/ModalBody.js
  packages/react-styled-ui/src/Modal/ModalFooter.js
  packages/react-styled-ui/src/Modal/ModalHeader.js
  packages/react-styled-ui/src/Popover/PopoverHeader.js
  packages/react-styled-ui/src/Popper/Popper.js
  packages/react-styled-ui/src/PseudoBox/index.js
  packages/react-styled-ui/src/SVGIcon/index.js
  packages/react-styled-ui/src/Scrollbar/Scrollbar.js
  packages/react-styled-ui/src/Scrollbar/renderDefaultElements.js
  packages/react-styled-ui/src/Select/Option.js
  packages/react-styled-ui/src/Select/OptionGroup.js
  packages/react-styled-ui/src/Select/Select.js
  packages/react-styled-ui/src/Spinner/index.js
  packages/react-styled-ui/src/Table/TableCell.js
  packages/react-styled-ui/src/Table/TableHeaderCell.js
  packages/react-styled-ui/src/Table/TableRow.js
  packages/react-styled-ui/src/Tag/index.js
  packages/react-styled-ui/src/ToastProvider/ToastTransition.js
  packages/react-styled-ui/src/ToggleSwitch/index.js
  packages/react-styled-ui/src/index.js
  packages/styled-ui-docs/components/AnimatedCubeDemo.jsx
  packages/styled-ui-docs/components/CodeBlock.jsx
  packages/styled-ui-docs/components/Header.jsx
  packages/styled-ui-docs/components/SideNav.jsx
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/box.mdx
  packages/styled-ui-docs/pages/pseudobox.mdx
  packages/styled-ui-docs/pages/tag.mdx
Labels: 👷 refactor (improvement), 🏗️ work in progress

#373 docs: add icon button example
  packages/styled-ui-docs/components/nav-links.js
  packages/styled-ui-docs/pages/buttonbase.mdx
  packages/styled-ui-docs/pages/iconbutton.mdx
Labels: 📝 documentation

#381 docs(eslint): component definition is missing display name
  packages/docs/components/EditableTag.jsx
  packages/docs/components/FontAwesomeIcon.jsx
  packages/docs/components/Header.jsx
  packages/docs/components/Main.jsx
  packages/docs/components/NavLink.jsx
  packages/docs/components/SideNav.jsx
Labels: 📝 documentation

#382 fix: add the onBlur prop to MenuList will override default onBlur event handler (#327)
  packages/react/src/Menu/MenuList.js
Labels: 🐛 bug

#375 docs: improve documentation
  packages/docs/components/CodeBlock.jsx
  packages/docs/components/MDXComponents.jsx
  packages/docs/package.json
  packages/docs/pages/contributing.mdx
  packages/docs/pages/getting-started.mdx
  packages/docs/pages/menu.mdx
Labels: 📝 documentation, 🏗️ work in progress

#385 feat: add support for the `colorScheme` property (#379)
  packages/docs/components/MDXComponents.jsx
  packages/docs/pages/_app.js
  packages/docs/pages/color-mode.mdx
  packages/docs/pages/getting-started.mdx
  packages/react/src/DarkMode/index.js
  packages/react/src/LightMode/index.js
  packages/react/src/shared/styled-system/config.js
Labels: 🎉 feature (enhancement)

#388 feat: add DOM helper library
  packages/react/src/Popper/Popper.js
  packages/react/src/Portal/index.js
  packages/react/src/ToastProvider/ToastProvider.js
  packages/react/src/utils/dom.js
  packages/react/src/utils/dom/canUseDOM.js
  packages/react/src/utils/dom/contains.js
  packages/react/src/utils/dom/focusableSelector.js
  packages/react/src/utils/dom/getComputedStyle.js
  packages/react/src/utils/dom/getWindow.js
  packages/react/src/utils/dom/isFocusable.js
  packages/react/src/utils/dom/ownerDocument.js
  packages/react/src/utils/dom/ownerWindow.js
  packages/react/src/utils/getFocusableElements.js
  packages/react/src/utils/useEnhancedEffect.js
  packages/react/src/utils/useIsomorphicLayoutEffect.js
  packages/react/src/utils/useNodeRef.js
Labels: 🎉 feature (enhancement)

#380 refactor(Scrollbar): use `overflow`, `overflowX`, `overflowY` properties to specify whether to change the content overflow only vertically or horizontally (or both)
  packages/docs/pages/scrollbar.mdx
  packages/docs/pages/table.mdx
  packages/react/src/Scrollbar/HorizontalThumb.js
  packages/react/src/Scrollbar/HorizontalTrack.js
  packages/react/src/Scrollbar/ScrollView.js
  packages/react/src/Scrollbar/Scrollbar.js
  packages/react/src/Scrollbar/VerticalThumb.js
  packages/react/src/Scrollbar/VerticalTrack.js
  packages/react/src/Scrollbar/renderDefaultElements.js
  packages/react/src/Scrollbar/styles.js
  packages/react/src/Scrollbar/utils/getInnerHeight.js
  packages/react/src/Scrollbar/utils/getInnerWidth.js
  packages/react/src/Scrollbar/utils/getScrollbarWidth.js
  packages/react/src/Skeleton/index.js
Labels: 👷 refactor (improvement), 💣 breaking change

#361 breaking: remove isHoverable prop from Table
  packages/docs/pages/tabs.mdx
  packages/react/src/Table/Table.js
  packages/react/src/Table/TableRow.js
Labels: 💣 breaking change, deprecated
