Repository trendmicro-frontend/tonic-ui, pull requests merged in 2021-05, with the labels that each got.

#305 chore(styled-ui-theme): add back deprecated shadow properties for backward compatibility
  packages/styled-ui-theme/src/foundations/shadows.js
  packages/styled-ui-theme/test/index.js
Labels: deprecated

#291 fix(tab): fix incorrect border color for the selected tab that receives focus (part 2)
  packages/react-styled-ui/src/Tabs/styles.js
Labels: 🔎 review required

#307 docs: fix an issue that the optional chaining operator is not supported for the code block
  packages/styled-ui-docs/pages/stack.mdx
  packages/styled-ui-docs/pages/toast.mdx
Labels: 🐛 bug, 📝 documentation

#311 docs: adjust the example for Tag component
  packages/react-styled-ui/src/Tag/styles.js
  packages/styled-ui-docs/components/EditableTag.jsx
  packages/styled-ui-docs/pages/tag.mdx
Labels: 🐛 bug, 📝 documentation
