Repository trendmicro-frontend/tonic-ui, pull requests merged in 2021-01, with the labels that each got.

#267 feat: enable website tracking using Google Analytics
  packages/styled-ui-docs/next.config.js
  packages/styled-ui-docs/package.json
  packages/styled-ui-docs/pages/_app.js
Labels: 🎉 feature (enhancement)

#268 fix color page and remove heading style
  packages/styled-ui-docs/components/ColorPalette.jsx
  packages/styled-ui-docs/components/ThemeParser.jsx
  packages/styled-ui-docs/pages/colors.mdx
  packages/styled-ui-docs/pages/getting-started.mdx
  packages/styled-ui-docs/pages/typography.mdx
  packages/styled-ui-theme/src/foundations/fonts.js
  packages/styled-ui-theme/test/index.js
  yarn.lock
Labels: 🎉 feature (enhancement), 🔎 review required

#271 fix: fix some issues for Menu component
  packages/react-styled-ui/src/Menu/MenuItem.js
  packages/react-styled-ui/src/Menu/MenuList.js
  packages/styled-ui-docs/pages/menu.mdx
Labels: 🐛 bug
