Repository trendmicro-frontend/tonic-ui, pull requests merged in 2022-09, with the labels that each got.

#618 ci: resolve warnings when building `react-docs` with the `next.config.js` file
  packages/react-docs/next.config.mjs
  packages/react-docs/package.json
Labels: 🧱 build (ci/cd)

#619 docs: adjust Toast sample code for smooth animation
  packages/react-docs/pages/components/toast.mdx
Labels: 📝 documentation

#620 docs: adjust Toast sample code for smooth animation
  packages/docs/pages/toast.mdx
Labels: 📝 documentation, v0

#622 docs: adjust Toast sample code (Part II)
  packages/docs/pages/toast.mdx
Labels: v0

#624 feat: remove `outline: none` from `Link` component to improve accessibility with keyboard navigation
  packages/react-docs/components/GlobalStyles.jsx
  packages/react/src/link/styles.js
Labels: 🎉 feature (enhancement)

#617 feat: rework `SearchInput` component
  packages/react-docs/pages/components/searchinput.mdx
  packages/react/src/search-input/SearchInput.js
  packages/react/src/search-input/SearchInputCloseButton.js
  packages/react/src/search-input/split-props.js
  packages/react/src/search-input/styles.js
Labels: 🐛 bug, 🎉 feature (enhancement)
