Repository trendmicro-frontend/tonic-ui, pull requests merged in 2022-03, with the labels that each got.

#498 feat(`react-hooks`): add `useEventCallback` Hook
  packages/react-docs/components/nav-links.js
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/hooks/use-event-callback.mdx
  packages/react-hooks/src/index.js
  packages/react-hooks/src/useEventCallback.js
  packages/react-hooks/src/useEventCallback.test.js
Labels: 🎉 feature (enhancement)

#493 feat: rework `Tabs` component
  packages/react-docs/components/FontAwesomeIcon.jsx
  packages/react-docs/components/GlobalStyles.jsx
  packages/react-docs/components/Header.jsx
  packages/react-docs/components/MDXComponents.jsx
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/tabs.mdx
  packages/react/src/index.js
  packages/react/src/shared/color-style.js
  packages/react/src/tabs/Tab.js
  packages/react/src/tabs/TabList.js
  packages/react/src/tabs/TabPanel.js
  packages/react/src/tabs/TabPanels.js
  packages/react/src/tabs/Tabs.js
  packages/react/src/tabs/context.js
  packages/react/src/tabs/index.js
  packages/react/src/tabs/styles.js
  packages/react/src/tabs/useTabs.js
  packages/react/test/index.js
Labels: 👷 refactor (improvement), 🏗️ work in progress

#506 fix(v0): adjust backdrop style to fix unexpected component position change
  packages/react/src/Drawer/DrawerContent.js
  packages/react/src/Modal/ModalContent.js
Labels: 🐛 bug

#505 fix: adjust backdrop style to fix unexpected component position change
  packages/react/src/drawer/DrawerContent.js
  packages/react/src/modal/ModalContent.js
Labels: 🐛 bug

#503 feat: add new React Hooks - `useCopyToClipboard`, `useEffectOnceWhen`, `useMediaQuery`, `useOnce`, `useOnceWhen`
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/hooks/use-effect-once.mdx
  packages/react-docs/pages/hooks/useConst.mdx
  packages/react-docs/pages/hooks/useCopyToClipboard.mdx
  packages/react-docs/pages/hooks/useEffectOnce.mdx
  packages/react-docs/pages/hooks/useEffectOnceWhen.mdx
  packages/react-docs/pages/hooks/useEventCallback.mdx
  packages/react-docs/pages/hooks/useHydrated.mdx
  packages/react-docs/pages/hooks/useIsomorphicEffect.mdx
  packages/react-docs/pages/hooks/useLatest.mdx
  packages/react-docs/pages/hooks/useMediaQuery.mdx
  packages/react-docs/pages/hooks/useOnce.mdx
  packages/react-docs/pages/hooks/useOnceWhen.mdx
  packages/react-docs/pages/hooks/usePrevious.mdx
  packages/react-docs/pages/hooks/useToggle.mdx
  packages/react-hooks/src/index.js
  packages/react-hooks/src/useConst.js
  packages/react-hooks/src/useConst.test.js
  packages/react-hooks/src/useCopyToClipboard.js
  packages/react-hooks/src/useCopyToClipboard.test.js
  packages/react-hooks/src/useEffectOnce.js
  packages/react-hooks/src/useEffectOnce.test.js
  packages/react-hooks/src/useEffectOnceWhen.js
  packages/react-hooks/src/useEffectOnceWhen.test.js
  packages/react-hooks/src/useEventCallback.test.js
  packages/react-hooks/src/useHydrated.test.js
  packages/react-hooks/src/useLatest.test.js
  packages/react-hooks/src/useMediaQuery.js
  packages/react-hooks/src/useMediaQuery.test.js
  packages/react-hooks/src/useOnce.js
  packages/react-hooks/src/useOnce.test.js
  packages/react-hooks/src/useOnceWhen.js
  packages/react-hooks/src/useOnceWhen.test.js
  packages/react-hooks/src/usePrevious.test.js
  packages/react-hooks/src/useToggle.test.js
  packages/react/src/alert/Alert.js
  packages/react/src/badge/Badge.js
  packages/react/src/box/PseudoBox.js
  packages/react/src/deprecated/useDisclosure.js
  packages/react/src/drawer/Drawer.js
  packages/react/src/modal/Modal.js
  packages/react/src/popover/PopoverTrigger.js
  packages/react/src/scrollbar/Scrollbar.js
  packages/react/src/switch/ToggleSwitch.js
  packages/react/src/table/Table.js
  packages/react/src/tabs/Tab.js
  packages/react/src/tabs/TabPanel.js
  packages/react/src/tag/Tag.js
  packages/react/src/theme/withTheme.js
  packages/react/src/toast/Toast.js
  packages/react/src/tooltip/Tooltip.js
Labels: 🎉 feature (enhancement)

#492 feat: rework `Tag` component and deprecate unwanted props
  packages/react-docs/components/CodeBlock.jsx
  packages/react-docs/components/EditableTag.jsx
  packages/react-docs/components/InputTag/AutosizeInput.js
  packages/react-docs/components/InputTag/EditableTag.js
  packages/react-docs/components/InputTag/InputTag.js
  packages/react-docs/components/InputTag/TagCreator.js
  packages/react-docs/components/InputTag/index.js
  packages/react-docs/components/InputTag/styles.js
  packages/react-docs/components/InputTag/wrapEvent.js
  packages/react-docs/pages/components/tag.mdx
  packages/react/src/tag/Tag.js
  packages/react/src/tag/TagCloseButton.js
  packages/react/src/tag/styles.js
  packages/react/src/tag/test/Tag.test.js
Labels: 👷 refactor (improvement)

#515 feat: allow the entire modal content to scroll within the viewport
  packages/react-docs/components/CodeBlock.jsx
  packages/react-docs/pages/components/modal.mdx
  packages/react/src/alert/index.js
  packages/react/src/modal/Modal.js
  packages/react/src/modal/ModalBody.js
  packages/react/src/modal/ModalCloseButton.js
  packages/react/src/modal/ModalContainer.js
  packages/react/src/modal/ModalContent.js
  packages/react/src/modal/index.js
  packages/react/src/modal/styles.js
  packages/react/src/tag/index.js
  packages/react/src/toast/index.js
  packages/react/test/index.js
Labels: 🎉 feature (enhancement)

#517 docs: add examples for `ButtonLink` and `VisuallyHidden` components
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/buttonlink.mdx
  packages/react-docs/pages/components/presence.mdx
  packages/react-docs/pages/components/visually-hidden.mdx
  packages/react/src/drawer/Drawer.js
  packages/react/src/drawer/DrawerContent.js
  packages/react/src/drawer/DrawerOverlay.js
  packages/react/src/index.js
  packages/react/src/modal/Modal.js
  packages/react/src/modal/ModalContainer.js
  packages/react/src/modal/ModalOverlay.js
  packages/react/src/presence/context.js
  packages/react/src/presence/index.js
  packages/react/src/utils/animate-presence/AnimatePresence.js
  packages/react/src/utils/animate-presence/context.js
  packages/react/src/utils/animate-presence/index.js
  packages/react/src/utils/animate-presence/useAnimatePresence.js
  packages/react/test/index.js
Labels: 📝 documentation

#520 fix: bug fixes for modal outside scrolling
  packages/react-docs/pages/components/modal.mdx
  packages/react/src/modal/Modal.js
  packages/react/src/modal/ModalContainer.js
  packages/react/src/modal/ModalContent.js
  packages/react/src/modal/styles.js
Labels: 🐛 bug

#521 feat: rework `Drawer` component
  packages/react-docs/pages/components/drawer.mdx
  packages/react-docs/pages/components/modal.mdx
  packages/react/src/drawer/Drawer.js
  packages/react/src/drawer/DrawerBody.js
  packages/react/src/drawer/DrawerCloseButton.js
  packages/react/src/drawer/DrawerContainer.js
  packages/react/src/drawer/DrawerContent.js
  packages/react/src/drawer/index.js
  packages/react/src/drawer/styles.js
  packages/react/test/index.js
Labels: 🏗️ work in progress

#524 fix(`v0`): bug fixes for modal outside scrolling
  packages/react/src/Modal/ModalContent.js
  packages/react/src/Modal/styles.js
Labels: 🐛 bug

#534 feat: export component Hooks and allow accessing internal context from component providers
  packages/react-docs/pages/components/accordion.mdx
  packages/react-docs/pages/components/checkboxgroup.mdx
  packages/react-docs/pages/components/drawer.mdx
  packages/react-docs/pages/components/inputgroup.mdx
  packages/react-docs/pages/components/menu.mdx
  packages/react-docs/pages/components/modal.mdx
  packages/react-docs/pages/components/radiogroup.mdx
  packages/react-docs/pages/components/toast.mdx
  packages/react/src/accordion/index.js
  packages/react/src/checkbox/CheckboxGroup.js
  packages/react/src/drawer/Drawer.js
  packages/react/src/input/InputGroup.js
  packages/react/src/menu/index.js
  packages/react/src/modal/Modal.js
  packages/react/src/radio/RadioGroup.js
  packages/react/src/toast/ToastProvider.js
  packages/react/test/index.js
Labels: 🎉 feature (enhancement)

#537 breaking: deprecate the rarely used `FlatButton` component
  packages/react-docs/components/CodeBlock.jsx
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/alert.mdx
  packages/react-docs/pages/components/buttonbase.mdx
  packages/react-docs/pages/components/flatbutton.mdx
  packages/react-docs/pages/components/toast.mdx
  packages/react-docs/pages/getting-started/migration-v0x.mdx
  packages/react/src/deprecated/FlatButton.js
  packages/react/src/flat-button/FlatButton.js
  packages/react/src/flat-button/index.js
  packages/react/src/flat-button/styles.js
  packages/react/src/index.js
  packages/react/test/index.js
Labels: 💣 breaking change

#540 feat: rework Spinner component
  packages/react-docs/pages/components/spinner.mdx
  packages/react-docs/pages/getting-started/migration-v0x.mdx
  packages/react/src/spinner/Spinner.js
  packages/react/src/spinner/styles.js
Labels: 🎉 feature (enhancement), 💣 breaking change

#535 feat: remove the `color` package for security consideration
  packages/react-docs/components/Header.jsx
  packages/react-docs/package.json
  packages/react-docs/pages/components/buttongroup.mdx
  packages/react-docs/pages/components/divider.mdx
  packages/react-docs/pages/index.js
  packages/react/package.json
  packages/react/src/button/Button.js
  packages/react/src/button/ButtonGroup.js
  packages/react/src/button/styles.js
  packages/react/src/divider/Divider.js
  packages/react/src/divider/styles.js
  packages/react/src/menu/styles.js
  packages/react/src/pagination/Pagination.js
  packages/react/src/pagination/styles.js
  packages/react/src/utils/colors.js
Labels: 🎉 feature (enhancement), 🔎 review required, security

#543 feat: add selected state to the `Button` component
  packages/react-docs/components/CodeBlock.jsx
  packages/react-docs/components/SelectButton.jsx
  packages/react-docs/pages/components/button.mdx
  packages/react-docs/pages/components/buttongroup.mdx
  packages/react-docs/pages/components/drawer.mdx
  packages/react-docs/pages/components/menu.mdx
  packages/react-docs/pages/components/modal.mdx
  packages/react-docs/pages/components/stack.mdx
  packages/react-docs/pages/components/transitions/slide.mdx
  packages/react/src/button/Button.js
  packages/react/src/button/styles.js
Labels: 🎉 feature (enhancement)

#544 docs: add color style usage to the getting started guide
  packages/react-docs/components/MDXComponents.jsx
  packages/react-docs/pages/getting-started/usage.mdx
Labels: 📝 documentation

#546 docs: add an example that navigates multiple alert notifications using the pagination method
  packages/react-docs/pages/components/alert.mdx
Labels: 📝 documentation

#545 breaking: deprecate the second argument of `CheckboxGroup`'s `onChange` callback
  packages/react-docs/pages/getting-started/migration-v0x.mdx
  packages/react/src/checkbox/CheckboxGroup.js
  packages/react/src/utils/once.js
Labels: 💣 breaking change
