Repository trendmicro-frontend/tonic-ui, pull requests merged in 2022-04, with the labels that each got.

#557 feat: add `useEventListener` Hook
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/hooks/useEventListener.mdx
  packages/react-hooks/src/index.js
  packages/react-hooks/src/useEventListener.js
  packages/react-hooks/src/useEventListener.test.js
Labels: 🎉 feature (enhancement)

#555 feat: rework `Tooltip` component
  packages/react-docs/pages/components/text.mdx
  packages/react-docs/pages/components/tooltip.mdx
  packages/react-hooks/src/useMediaQuery.js
  packages/react/src/popover/Popover.js
  packages/react/src/tooltip/Tooltip.js
  packages/react/src/tooltip/TooltipContent.js
  packages/react/src/tooltip/TooltipTrigger.js
  packages/react/src/tooltip/context.js
  packages/react/src/tooltip/styles.js
  packages/react/src/tooltip/useTooltip.js
  packages/react/src/utils/isBlankString.js
  packages/react/src/utils/isBlankString.test.js
  packages/react/src/utils/isEmptyArray.js
  packages/react/src/utils/isEmptyArray.test.js
  packages/react/src/utils/isEmptyObject.js
  packages/react/src/utils/isEmptyObject.test.js
  packages/react/src/utils/isNullOrUndefined.test.js
  packages/react/src/utils/isWhitespace.js
  packages/react/src/utils/isWhitespace.test.js
  packages/react/src/utils/refs.js
Labels: 📝 documentation, 👷 refactor (improvement), 🎉 feature (enhancement)

#560 feat: add `Truncate` component
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/tooltip.mdx
  packages/react-docs/pages/components/truncate.mdx
  packages/react/src/index.js
  packages/react/src/tooltip/styles.js
  packages/react/src/truncate/Truncate.js
  packages/react/src/truncate/index.js
  packages/react/src/truncate/styles.js
  packages/react/test/index.js
Labels: 🎉 feature (enhancement)

#565 fix: fix a performance issue in `Popper` that would cause infinite loop with `setState`
  packages/react/src/menu/MenuList.js
  packages/react/src/popover/Popover.js
  packages/react/src/popover/PopoverContent.js
  packages/react/src/popper/Popper.js
  packages/react/src/tooltip/Tooltip.js
  packages/react/src/tooltip/TooltipContent.js
Labels: 🐛 bug

#566 fix: fix a performance issue in `Popper` that would cause infinite loop with `setState`
  packages/docs/.eslintrc.js
  packages/react/src/Popper/Popper.js
Labels: 🐛 bug, v0

#561 feat: rework `Popover` component
  packages/react-docs/pages/components/menu.mdx
  packages/react-docs/pages/components/popover.mdx
  packages/react-docs/pages/components/tabs.mdx
  packages/react-docs/pages/components/tooltip.mdx
  packages/react/src/menu/Menu.js
  packages/react/src/menu/MenuList.js
  packages/react/src/popover/Popover.js
  packages/react/src/popover/PopoverBody.js
  packages/react/src/popover/PopoverContent.js
  packages/react/src/popover/PopoverHeader.js
  packages/react/src/popover/PopoverTrigger.js
  packages/react/src/popover/context.js
  packages/react/src/popover/index.js
  packages/react/src/popover/styles.js
  packages/react/src/popover/usePopover.js
  packages/react/src/tabs/Tabs.js
  packages/react/src/tooltip/Tooltip.js
  packages/react/src/tooltip/TooltipContent.js
  packages/react/src/tooltip/TooltipTrigger.js
  packages/react/test/index.js
Labels: 👷 refactor (improvement)

#574 fix: correct the demo of `_nthOfType`
  packages/react-docs/pages/styled-system/pseudo-style-props.mdx.template
Labels: 📝 documentation

#575 feat: rework `Calendar` and `DatePicker` component props
  packages/react-docs/components/CodeBlock.jsx
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/inputcontrol.mdx
  packages/react-docs/pages/components/modal.mdx
  packages/react-docs/pages/lab/date-pickers/Calendar.mdx
  packages/react-docs/pages/lab/date-pickers/DatePicker.mdx
  packages/react-docs/pages/lab/date-pickers/index.mdx
  packages/react-docs/pages/lab/date-time-pickers/Calendar.mdx
  packages/react-lab/src/date-pickers/Calendar/Calendar.js
  packages/react-lab/src/date-pickers/Calendar/MonthView/Day.js
  packages/react-lab/src/date-pickers/Calendar/MonthView/DaysOfWeek.js
  packages/react-lab/src/date-pickers/Calendar/MonthView/Week.js
  packages/react-lab/src/date-pickers/Calendar/MonthView/Weeks.js
  packages/react-lab/src/date-pickers/Calendar/MonthView/index.js
  packages/react-lab/src/date-pickers/Calendar/Navigation.js
  packages/react-lab/src/date-pickers/Calendar/context.js
  packages/react-lab/src/date-pickers/Calendar/index.js
  packages/react-lab/src/date-pickers/Calendar/styles.js
  packages/react-lab/src/date-pickers/Calendar/useCalendar.js
  packages/react-lab/src/date-pickers/DatePicker/DatePicker.js
  packages/react-lab/src/date-pickers/DatePicker/DatePickerContent.js
  packages/react-lab/src/date-pickers/DatePicker/DatePickerToggle.js
  packages/react-lab/src/date-pickers/DatePicker/context.js
  packages/react-lab/src/date-pickers/DatePicker/index.js
  packages/react-lab/src/date-pickers/DatePicker/styles.js
  packages/react-lab/src/date-pickers/DatePicker/useDatePicker.js
  packages/react-lab/src/date-pickers/DatePicker/useOutsideClick.js
  packages/react-lab/src/date-pickers/index.js
  packages/react-lab/src/date-pickers/validation.js
  packages/react-lab/src/date-time-pickers/Calendar/Calendar.js
  packages/react-lab/src/date-time-pickers/Calendar/MonthView/Day.js
  packages/react-lab/src/date-time-pickers/Calendar/MonthView/Week.js
  packages/react-lab/src/date-time-pickers/Calendar/Navigation.js
  packages/react-lab/src/date-time-pickers/DatePicker/DatePicker.js
  packages/react-lab/src/index.js
  packages/react-lab/src/utils/dom/getComputedStyle.js
  packages/react-lab/src/utils/dom/getFocusableElementSelectors.js
  packages/react-lab/src/utils/getFocusableElements.js
  packages/react-lab/src/utils/isNullOrUndefined.js
  packages/react-lab/src/utils/runIfFn.js
  packages/react/src/shared/config.js
Labels: 🎉 feature (enhancement)
