Repository trendmicro-frontend/tonic-ui, pull requests merged in 2024-07, with the labels that each got.

#883 docs: enhance Contribution Guide and Migration Guide
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/icon/index.page.mdx
  packages/react-docs/pages/contribution-guide/index.page.mdx
  packages/react-docs/pages/contribution-guide/publishing.page.mdx
  packages/react-docs/pages/contribution-guide/react-components-part-1-example.js
  packages/react-docs/pages/contribution-guide/react-components-part-1.page.mdx
  packages/react-docs/pages/contribution-guide/react-components-part-2.page.mdx
  packages/react-docs/pages/contribution-guide/react-documentation-site.page.mdx
  packages/react-docs/pages/contribution-guide/react-icons.page.mdx
  packages/react-docs/pages/getting-started/icons/index.page.mdx
  packages/react-docs/pages/migration-guide/migrating-from-v0-to-v1.page.mdx
  packages/react-docs/pages/migration-guide/migrating-from-v1-to-v2.page.mdx
Labels: Enhancement, Review effort [1-5]: 2, Documentation

#884 ci: enhance monorepo release flow with `changesets`
  .changeset/README.md
  .changeset/config.json
  .github/workflows/changesets-release.yml
  package.json
  yarn.lock
Labels: Review effort [1-5]: 3, Enhancement, Configuration changes

#894 fix(react/OverflowTooltip): resolve tooltip misalignment issue with popup menu items
  .changeset/tonic-ui-893.md
  .circleci/config.yml
  packages/react-docs/pages/components/overflow-tooltip/faq-misalignment-with-menu-items.js
  packages/react-docs/pages/components/overflow-tooltip/faq-relative-to-reference-element.js
  packages/react-docs/pages/components/overflow-tooltip/faq-tooltip-cut-off.js
  packages/react-docs/pages/components/overflow-tooltip/index.page.mdx
  packages/react-docs/pages/components/tooltip/index.page.mdx
  packages/react-docs/pages/components/tooltip/positioning-follow-cursor.js
  packages/react-docs/pages/components/tooltip/positioning-next-cursor.js
  packages/react-docs/pages/components/tooltip/positioning-offset.js
  packages/react/src/popover/styles.js
  packages/react/src/tooltip/OverflowTooltip.js
  packages/react/src/tooltip/TooltipContent.js
  packages/react/src/tooltip/styles.js
  packages/react/src/tree/TreeItem.js
  packages/react/src/utils/__tests__/pixelize.test.js
  packages/react/src/utils/pixelize.js
Labels: 🐛 bug, Review effort [1-5]: 3, Documentation

#897 feat(react): improve tooltip placement and offset calculations
  .changeset/tonic-ui-893b.md
  packages/react-docs/pages/components/overflow-tooltip/faq-relative-to-reference-element.js
  packages/react-docs/pages/components/overflow-tooltip/index.page.mdx
  packages/react-docs/pages/components/tooltip/index.page.mdx
  packages/react-docs/pages/components/tooltip/positioning-follow-cursor.js
  packages/react-docs/pages/components/tooltip/positioning-next-cursor.js
  packages/react-docs/pages/components/tooltip/positioning-offset.js
  packages/react/src/tooltip/OverflowTooltip.js
  packages/react/src/tooltip/Tooltip.js
  packages/react/src/tooltip/TooltipContent.js
Labels: Review effort [1-5]: 3, Enhancement, Documentation

#899 docs: update usage for using as="li" for Text component
  packages/react-docs/pages/components/text/index.page.mdx
  packages/react-docs/pages/components/text/text-as-li.js
Labels: Documentation, Review effort [1-5]: 1

#901 docs: prevent type errors in `InstantSearchRefinementList`
  packages/react-docs/components/InstantSearchRefinementList.js
Labels: Review effort [1-5]: 2, Documentation, Bug fix

#902 docs: enforce string format to ensure Algolia search indexing functions correctly
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/scripts/algolia-search-indexing.js
Labels: Enhancement, Review effort [1-5]: 2, Documentation
