Repository trendmicro-frontend/tonic-ui, pull requests merged in 2024-09, with the labels that each got.

#918 feat(react-icons): refine `generate-icons` script to enhance icon name transformation and support deprecated icons
  .changeset/tonic-ui-react-icons-tmicon-1.41.0.md
  packages/react-docs/pages/icons/search-icons.js
  packages/react-icons/package.json
  packages/react-icons/scripts/generate-icons.mjs
  packages/react-icons/src/icons/AISecurityIcon.js
  packages/react-icons/src/icons/APIIcon.js
  packages/react-icons/src/icons/APIManagementIcon.js
  packages/react-icons/src/icons/ConnectNoIPIcon.js
  packages/react-icons/src/icons/FilePDFOIcon.js
  packages/react-icons/src/icons/FilePPTOIcon.js
  packages/react-icons/src/icons/FileUnzipOIcon.js
  packages/react-icons/src/icons/IAMIcon.js
  packages/react-icons/src/icons/IEIcon.js
  packages/react-icons/src/icons/IOCIcon.js
  packages/react-icons/src/icons/IPIcon.js
  packages/react-icons/src/icons/ListOLIcon.js
  packages/react-icons/src/icons/ListULIcon.js
  packages/react-icons/src/icons/NASIcon.js
  packages/react-icons/src/icons/RCAIcon.js
  packages/react-icons/src/icons/ResizeNESWIcon.js
  packages/react-icons/src/icons/ResizeNWSEIcon.js
  packages/react-icons/src/icons/SecurityAIIcon.js
  packages/react-icons/src/icons/TVIcon.js
  packages/react-icons/src/icons/URLIcon.js
  packages/react-icons/src/icons/USBIcon.js
  packages/react-icons/src/icons/WMIIcon.js
  packages/react-icons/src/icons/deprecated/ApiIcon.js
  packages/react-icons/src/icons/deprecated/ApiManagementIcon.js
  packages/react-icons/src/icons/deprecated/ConnectNoipIcon.js
  packages/react-icons/src/icons/deprecated/FilePdfOIcon.js
  packages/react-icons/src/icons/deprecated/FilePptOIcon.js
  packages/react-icons/src/icons/deprecated/IamIcon.js
  packages/react-icons/src/icons/deprecated/IeIcon.js
  packages/react-icons/src/icons/deprecated/IocIcon.js
  packages/react-icons/src/icons/deprecated/IpIcon.js
  packages/react-icons/src/icons/deprecated/ListOlIcon.js
  packages/react-icons/src/icons/deprecated/ListUlIcon.js
  packages/react-icons/src/icons/deprecated/NasIcon.js
  packages/react-icons/src/icons/deprecated/RcaIcon.js
  packages/react-icons/src/icons/deprecated/ResizeNeswIcon.js
  packages/react-icons/src/icons/deprecated/ResizeNwseIcon.js
  packages/react-icons/src/icons/deprecated/TvIcon.js
  packages/react-icons/src/icons/deprecated/UrlIcon.js
  packages/react-icons/src/icons/deprecated/UsbIcon.js
  packages/react-icons/src/icons/deprecated/WmiIcon.js
  packages/react-icons/src/icons/index.js
  yarn.lock
Labels: Review effort [1-5]: 3, Enhancement, Documentation, bug_fix

#925 fix(react/tooltip): resolve tooltip misalignment issue with popup modal items for V1
  .changeset/tonic-ui-893-v1.md
  packages/react-docs/pages/components/overflow-tooltip/faq-misalignment-with-menu-items.js
  packages/react-docs/pages/components/overflow-tooltip/faq-tooltip-cut-off.js
  packages/react-docs/pages/components/overflow-tooltip/index.page.mdx
  packages/react-docs/pages/components/tooltip/index.page.mdx
  packages/react-docs/pages/components/tooltip/positioning-follow-cursor.js
  packages/react-docs/pages/components/tooltip/positioning-next-cursor.js
  packages/react-docs/pages/components/tooltip/positioning-offset.js
  packages/react/src/popover/styles.js
  packages/react/src/tooltip/OverflowTooltip.js
  packages/react/src/tooltip/Tooltip.js
  packages/react/src/tooltip/TooltipContent.js
  packages/react/src/tooltip/styles.js
  packages/react/src/tree/TreeItem.js
  packages/react/src/utils/__tests__/pixelize.test.js
  packages/react/src/utils/pixelize.js
  yarn.lock
Labels: 🐛 bug, v1, Review effort [1-5]: 3, Enhancement, Tests, Documentation

#930 feat: improve `disabled` prop handling in `Button` and `ButtonGroup`
  .changeset/tonic-ui-927.md
  package.json
  packages/react-docs/components/Sidebar.js
  packages/react-docs/components/TableOfContents.js
  packages/react-docs/pages/components/button-group/index.page.mdx
  packages/react-docs/pages/components/checkbox-group/index.page.mdx
  packages/react-docs/pages/components/radio-group/index.page.mdx
  packages/react/src/button/Button.js
  packages/react/src/button/ButtonGroup.js
  packages/react/src/checkbox/Checkbox.js
  packages/react/src/checkbox/__tests__/Checkbox.test.js
  packages/react/src/radio/Radio.js
  packages/react/src/radio/__tests__/Radio.test.js
Labels: Review effort [1-5]: 3, Enhancement, Documentation

#935 fix: resolve bug with `isNameConflictRef.current` in `Checkbox` and `Radio` components
  .changeset/tonic-ui-927b.md
  packages/react/src/checkbox/Checkbox.js
  packages/react/src/radio/Radio.js
Labels: Review effort [1-5]: 2, Bug fix
