Repository trendmicro-frontend/tonic-ui, pull requests merged in 2025-04, with the labels that each got.

#991 feat: support `referenceRef` in `Popper` to address positioning issue
  .changeset/tonic-ui-990.md
  packages/react-docs/pages/components/menu/uncontrolled.js
  packages/react-docs/pages/components/popover/uncontrolled.js
  packages/react-docs/pages/components/tooltip/uncontrolled.js
  packages/react/src/date-pickers/DatePicker/DatePickerContent.js
  packages/react/src/menu/MenuContent.js
  packages/react/src/menu/SubmenuContent.js
  packages/react/src/popover/PopoverContent.js
  packages/react/src/popper/Popper.js
  packages/react/src/theme/__tests__/createTheme.test.js
  packages/react/src/toast/__tests__/Toast.test.js
  packages/react/src/toast/__tests__/ToastController.test.js
  packages/react/src/toast/__tests__/ToastManager.test.js
  packages/react/src/tooltip/TooltipContent.js
  packages/react/src/utils/__tests__/renderComponentOrValue.test.js
Labels: Review effort 2/5

#993 Fix: README contribution guide link
  README.md
Labels: Review effort 1/5

#996 fix(react/InputGroup): fix pseudo-class ':first-child' warning
  packages/react/src/input/styles.js
  packages/react/src/table/TableCell.js
Labels: Review effort 1/5

#999 feat(react/tag): update `_focus` to `_focusVisible` in `Tag` component to enable focus outline on keyboard navigation
  .changeset/tonic-ui-998.md
  packages/react/src/tag/styles.js
Labels: Review effort 2/5

#989 docs: update `Dropdown` component usage to allow tooltip display on overflow
  packages/react-docs/components/CodeBlock.js
  packages/react-docs/components/Dropdown.js
  packages/react-docs/components/DropdownBase.js
  packages/react-docs/components/FormGroup.js
  packages/react-docs/components/List.js
  packages/react-docs/components/ListItem.js
  packages/react-docs/components/Multiselect.js
  packages/react-docs/components/MutedText.js
  packages/react-docs/components/SearchDropdown.js
  packages/react-docs/components/Sidebar.js
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/package.json
  packages/react-docs/pages/components/menu/customization.js
  packages/react-docs/pages/components/menu/dropdown.js
  packages/react-docs/pages/components/menu/index.page.mdx
  packages/react-docs/pages/components/menu/menubutton.js
  packages/react-docs/pages/components/menu/menutoggle.js
  packages/react-docs/pages/components/menu/menutoggleicon-custom.js
  packages/react-docs/pages/components/menu/menutoggleicon.js
  packages/react-docs/pages/components/menu/multiselect.js
  packages/react-docs/pages/components/menu/placement.js
  packages/react-docs/pages/components/menu/positioning.js
  packages/react-docs/pages/components/menu/scrolling-native.js
  packages/react-docs/pages/components/menu/sizing-fixed-width.js
  packages/react-docs/pages/components/menu/sizing-full-width.js
  packages/react-docs/pages/components/menu/sizing-max-content.js
  packages/react-docs/pages/components/menu/sizing-min-content.js
  packages/react-docs/pages/experiments/Dropdown/index.page.mdx
  packages/react-docs/pages/experiments/Dropdown/usage.js
  packages/react-docs/pages/experiments/DropdownBase/index.page.mdx
  packages/react-docs/pages/experiments/DropdownBase/usage.js
  packages/react-docs/pages/experiments/List/index.page.mdx
  packages/react-docs/pages/experiments/List/usage.js
  packages/react-docs/pages/experiments/MutedText/index.page.mdx
  packages/react-docs/pages/experiments/MutedText/usage.js
  packages/react-docs/pages/experiments/SearchDropdown/index.page.mdx
  packages/react-docs/pages/experiments/SearchDropdown/multiple-selection.js
  packages/react-docs/pages/experiments/SearchDropdown/single-selection.js
  packages/react-docs/pages/experiments/index.page.mdx
  yarn.lock
Labels: Review effort 2/5

#1001 docs: add a copy button to the code block
  packages/react-docs/components/CodeBlock.js
  packages/react-docs/components/Demo.js
  packages/react-docs/components/MDXComponents.js
  packages/react-docs/package.json
  packages/react-docs/pages/experiments/index.page.mdx
  packages/react-docs/prism-themes/tonic-ui.js
  yarn.lock
Labels: Review effort 2/5

#1005 docs: enhance `DropdownBase` component to include support for `toggleProps` prop
  package.json
  packages/react-docs/components/Dropdown.js
  packages/react-docs/components/DropdownBase.js
  packages/react-docs/components/SearchDropdown.js
  packages/react-docs/pages/experiments/Dropdown/index.page.mdx
  packages/react-docs/pages/experiments/Dropdown/usage.js
  packages/react-docs/pages/experiments/DropdownBase/index.page.mdx
  packages/react-docs/pages/experiments/DropdownBase/usage.js
  packages/react-docs/pages/experiments/SearchDropdown/index.page.mdx
  packages/react-docs/pages/experiments/SearchDropdown/multi-select-dropdown.js
  packages/react-docs/pages/experiments/SearchDropdown/single-select-dropdown.js
Labels: Review effort 2/5

#1010 feat: support arbitrary value types for `CheckboxGroup` and `RadioGroup` components
  .changeset/tonic-ui-986.md
  packages/react-docs/pages/components/checkbox-group/arbitrary-value-types.js
  packages/react-docs/pages/components/checkbox-group/index.page.mdx
  packages/react-docs/pages/components/checkbox/index.page.mdx
  packages/react-docs/pages/components/radio-group/arbitrary-value-types.js
  packages/react-docs/pages/components/radio-group/index.page.mdx
  packages/react-docs/pages/components/radio/index.page.mdx
  packages/react/src/checkbox/Checkbox.js
  packages/react/src/checkbox/CheckboxGroup.js
  packages/react/src/checkbox/__tests__/Checkbox.test.js
  packages/react/src/checkbox/__tests__/CheckboxGroup.test.js
  packages/react/src/checkbox/__tests__/__snapshots__/CheckboxGroup.test.js.snap
  packages/react/src/radio/Radio.js
  packages/react/src/radio/RadioGroup.js
  packages/react/src/radio/__tests__/Radio.test.js
  packages/react/src/radio/__tests__/RadioGroup.test.js
  packages/react/src/radio/__tests__/__snapshots__/RadioGroup.test.js.snap
Labels: Review effort 3/5

#1014 feat(react/search-input): change `_focus` to `_focusVisible` for the close button in `SearchInput`
  .changeset/tonic-ui-998-search-input.md
  packages/react/src/search-input/styles.js
Labels: Review effort 2/5

#1013 fix(drawer): improve full-size drawer dimensions for full-screen span
  .changeset/tonic-ui-1012.md
  packages/react/src/drawer/DrawerContainer.js
  packages/react/src/drawer/styles.js
Labels: Review effort 1/5

#1017 feat: utilize `useClickOutside` hook to close modals and drawers when clicking outside the content
  .changeset/tonic-ui-987-react-hooks.md
  .changeset/tonic-ui-987.md
  packages/react-docs/config/sidebar-routes.js
  packages/react-docs/pages/components/drawer/index.page.mdx
  packages/react-docs/pages/components/drawer/usage.js
  packages/react-docs/pages/components/modal/index.page.mdx
  packages/react-docs/pages/components/modal/usage.js
  packages/react-docs/pages/components/table/usage.js
  packages/react-docs/pages/hooks/useClickOutside.js
  packages/react-docs/pages/hooks/useClickOutside.page.mdx
  packages/react-docs/pages/hooks/useOutsideClick.page.mdx
  packages/react-hooks/__tests__/index.test.js
  packages/react-hooks/src/__tests__/useClickOutside.test.js
  packages/react-hooks/src/__tests__/useOutsideClick.test.js
  packages/react-hooks/src/deprecated/useOutsideClick.js
  packages/react-hooks/src/index.js
  packages/react-hooks/src/useClickOutside.js
  packages/react-hooks/src/useOutsideClick.js
  packages/react/src/date-pickers/DatePicker/DatePicker.js
  packages/react/src/drawer/DrawerContainer.js
  packages/react/src/drawer/DrawerContent.js
  packages/react/src/modal/ModalContainer.js
  packages/react/src/modal/ModalContent.js
Labels: Review effort 2/5
