Repository trendmicro-frontend/tonic-ui, pull requests merged in 2025-06, with the labels that each got.

#1035 docs: use style props instead of `sx` for base components to simplify style overrides
  packages/react-docs/experiments/dropdown/Dropdown.js
  packages/react-docs/experiments/dropdown/DropdownBase.js
  packages/react-docs/experiments/search-dropdown/SearchDropdown.js
  packages/react-docs/pages/experiments/dropdown-base/index.page.mdx
  packages/react-docs/pages/experiments/dropdown-base/usage.js
  packages/react-docs/pages/experiments/dropdown/index.page.mdx
  packages/react-docs/pages/experiments/dropdown/usage.js
  packages/react-docs/pages/experiments/search-dropdown/index.page.mdx
  packages/react-docs/pages/experiments/search-dropdown/multi-select-dropdown.js
  packages/react-docs/pages/experiments/search-dropdown/single-select-dropdown.js
Labels: Review effort 1/5

#1038 revert(react/InputGroup): restore pseudo-class from 'first-of-type' to ':first-child' to align with ui spec
  .changeset/tonic-ui-pr-1038.md
  packages/react/src/input/styles.js
Labels: Bug fix, Review effort 2/5

#1033 feat: enable granular control over outside interactions for drawers and modals
  .changeset/tonic-ui-1032.md
  packages/react-docs/pages/components/drawer/index.page.mdx
  packages/react-docs/pages/components/drawer/usage.js
  packages/react-docs/pages/components/modal/index.page.mdx
  packages/react-docs/pages/components/modal/nested-modals.js
  packages/react-docs/pages/components/modal/usage.js
  packages/react-docs/pages/components/portal-manager/index.page.mdx
  packages/react-docs/pages/components/portal-manager/usePortalManager.js
  packages/react-docs/pages/components/table/column-visibility-and-order/column-settings-drawer.js
  packages/react-docs/pages/customization/shadow-dom.js
  packages/react-docs/pages/icons/search-icons.js
  packages/react-docs/pages/patterns/notification/drawer-alert.js
  packages/react-docs/pages/patterns/notification/drawer-toast.js
  packages/react-docs/pages/patterns/notification/modal-alert.js
  packages/react-docs/pages/patterns/notification/modal-toast.js
  packages/react-hooks/src/useClickOutside.js
  packages/react/src/drawer/Drawer.js
  packages/react/src/drawer/DrawerContent.js
  packages/react/src/drawer/__tests__/Drawer.test.js
  packages/react/src/modal/Modal.js
  packages/react/src/modal/ModalContainer.js
  packages/react/src/modal/ModalContent.js
  packages/react/src/modal/__tests__/Modal.test.js
Labels: 🎉 feature (enhancement), Review effort 2/5
